### ISSUE TITLE
Merge is good!

### ISSUE THREAD

**Issue by elovelan** [ZanderAdam/Svarog#1]
disagree with the comment at the bottom of this (can't seem to link to line numbers in GitHub mobile): https://github.com/ZanderAdam/Svarog/blob/master/src/libs/stage.js

Merge seems like the perfect way to override defaults

**Comment by ZanderAdam** [comment]
Agreed.

But at the moment I've got same configurations under multiple places (hence 3 way merge). There are the default settings, the settings defined directly under config and the settings under the staging.

In situations where there are different settings in both build config and staging sections, feel like there might be undesirable effects from the merge.
