### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by elovelan** [ZanderAdam/Svarog#2]
* The gulp ecosystem seems to be more function based than task based. Why did you choose to implement tasks?
* The answer to question 1 will help answer this but what does ``build`` provide over ``gulp-msbuild``?

**Comment by ZanderAdam** [comment]
1. To prove out the concept. Ideally it would be functions you call from your own gulpfile:

``` 
return gulp.src(solutionPath)
      .pipe(svarog.build(config);
```

 But it was easier to go this route at first. Need to refactor.

2. Abstraction and dependency management. No need to have the user managing both gulp-msbuild and svarog dependency. Just svarog. Also easier to replace the build component without impacting anything else that already uses it. High probability will have to go with a (nodejs implementation)[https://www.npmjs.com/package/msbuild] and not gulp one when its refactored to functions.

**Comment by ZanderAdam** [comment]
And now they are functions, not tasks.
